on: [push, pull_request]

name: Rust CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          # Linux
          # Minimum Supported Rust Version
          - TARGET=x86_64-unknown-linux-gnu RUN=1 NO_ADD=1
          # 32-bit
          - TARGET=i686-unknown-linux-gnu RUN=1
          # Fuchsia
          - TARGET=x86_64-fuchsia

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build and test
        run: |
          export ${{ matrix.env }}
          if [ -z "$NO_ADD" ]; then rustup target add "$TARGET"; fi
          cargo build --verbose --target="${TARGET}"
          if [ "${RUN}" == "1" ]; then cargo test --verbose --target "${TARGET}"; fi
