on: [push, pull_request]

name: Rust CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          # Linux
          # Minimum Supported Rust Version
          - x86_64-unknown-linux-gnu
          # Fuchsia
          - x86_64-fuchsia
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Build and test
        run: |
          cargo build --verbose --target=${{ matrix.target }}
